### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shivankgtm**
i am just beginning with open source Contribution if i have done something wrong please guide me.
i did what i understand i was supposed to do.

### CODE REVIEW

**Comment by shubhodeep9** [comment]
Hi @Shivank98 ,
1. Go through the existing issues, or you can create your own if you don't find any.
2. Discuss around the issue.
3. I will assign you the task.
4. Create fork.
5. Work and create pull request.
6. I will review and merge it with the branch.

**Comment by shivankgtm** [comment]
@shubhodeep9 
Thanks for helping 
I Updated the README.md now i think its your work further to review it

**Comment by shubhodeep9** [comment]
@Shivank98 I would like to first discuss it on the issue #2 , so why don't you leave a comment there and we will discuss how to create the readme.

**Review by shubhodeep9 — CHANGES_REQUESTED** [review]
Don't remove `> k.` and put the added line in another section as "Engineering behind the tool" something like that.

**Pull request closed without merging**
